# Name of your application. Used to uniquely configure containers.
service: rails-world

# Name of the container image.
image: ibramsterdam/rails-world

# To persist sqlite data, we need to mount a volume.
volumes:
  - storage:/rails/storage

# Credentials for your image host.
registry:
  username: ibramsterdam
  password:
    - KAMAL_REGISTRY_PASSWORD

# When running commands, you can specify a destination with the -d flag, e.g. kamal deploy -d staging
require_destination: true

